[server]
fileWatcherType = "none"
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
primaryColor = "#24634F"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#EDF1F4"
textColor = "#17252B"
font = "sans serif"
